version: "3.9"
services:
  client:
    build: ./client
    container_name: client
    restart: always
    env_file:
      - ./client/.env
    depends_on:
      - server
    ports:
      - "80:80"
    networks:
      - app-network

  server:
    build: ./server
    container_name: server
    restart: always
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    networks:
      - app-network
    expose:
      - "4000"

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
